services:
  - type: web
    name: betwisdom-football-analytics
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SPORTMONKS_API_KEY
        sync: false
    healthCheckPath: /